### ISSUE TITLE
run tests automatically with github actions

### ISSUE THREAD

**Issue by fyusuf-a** [fyusuf-a/ft_transcendence#22]

**Comment by tmorris42** [comment]
This is a good idea.

I had started a workflow for the backend, if you want to take a look
```
name: tests

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Backend Test and Lint
        run: |
          cd backend
          npm ci
          npm run lint -- --no-fix --max-warnings=0
          npm run test
```
